[[plugins]]
repo = 'plasticboy/vim-markdown'
oplasticboy/vim-markdownn_ft = 'markdown'

[[plugins]]
repo = 'previm/previm'
on_ft = 'markdown'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'

