# python plugins
[[plugins]]
repo = 'lambdalisue/vim-pyenv'
depends = [
  'jedi-vim',
]
on_ft = ['python']
hook_ad = '''
  function! s:jedi_auto_force_py_version() abort
	let g:jedi#force_py_version = pyenv#python#get_internal_major_version()
  endfunction
  augroup vim-pyenv-custom-augroup
	autocmd! *
	autocmd User vim-pyenv-activate-post   call s:jedi_auto_force_py_version()
	autocmd User vim-pyenv-deactivate-post call s:jedi_auto_force_py_version()
  augroup END
'''

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

