[[plugins]]
repo = 'Shougo/context_filetype.vim'

# lsp 扱えるようにする
[[plugins]]
repo = 'neoclide/coc.nvim'

# ステータスバーをリッチにする
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline#extensions#tabline#enabled = 1
'''

# コメントをいい感じにできる
[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
  nmap <C-_> <Plug>(caw:hatpos:toggle)
  vmap <C-_> <Plug>(caw:hatpos:toggle)
'''

# Git 周りをいい感じに
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'sonph/onehalf'
rtp = 'vim'

