# 左側のツリー表示
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let g:NERDTreeShowHidden=1
  map <C-n> :NERDTreeToggle<CR>
  autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
'''

# ステータスバーをリッチにする
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline#extensions#tabline#enabled = 1
'''

# 補完周り
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''

# vim lsp のクライアント
[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = '''
  set hidden
  filetype plugin indent on
  let g:LanguageClient_serverCommands = {
    \ 'javascript': ['typescript-language-server --stdio'],
    \ 'javascript.jsx': ['typescript-language-server --stdio'],
	\ 'typescript' : ['typescript-language-server --stdio'],
	\ 'typescript.tsx': ['typescript-language-server --stdio'],
	\ 'vue' : ['vls'],
	\ 'go': ['go-langserver','-gocodecompletion=true','-format-tool=gofmt','-lint-tool=golint'],
    \ }
  let g:LanguageClient_autoStart = 1

  nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
  nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
  nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
'''

# molokai のテーマ
[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  colorscheme molokai
  syntax on
  set t_Co=256
'''

# コメントをいい感じにできる
[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
  nmap <C-_> <Plug>(caw:hatpos:toggle)
  vmap <C-_> <Plug>(caw:hatpos:toggle)
'''

# Git 周りをいい感じに
[[plugins]]
repo = 'tpope/vim-fugitive'

# 言語ごとのプラグイン
[[plugins]]
repo = 'leafgarland/typescript-vim'
[[plugins]]
repo = 'posva/vim-vue'
[[plugins]]
repo = 'cespare/vim-toml'
