# Markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
oplasticboy/vim-markdownn_ft = 'markdown'

[[plugins]]
repo = 'previm/previm'
on_ft = 'markdown'
hook_add = '''
  let g:previm_open_cmd = 'open -a Vivaldi'
'''

[[plugins]]
repo = 'dsawardekar/wordpress.vim'
on_ft = 'php'
