# 左側のツリー表示
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let g:NERDTreeShowHidden=1
  map <C-n> :NERDTreeToggle<CR>
  autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
'''

# ステータスバーをリッチにする
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline#extensions#tabline#enabled = 1
'''

# 補完周り
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''

# molokai のテーマ
[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  colorscheme molokai
  syntax on
  set t_Co=256
'''

# コメントをいい感じにできる
[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
  nmap <C-_> <Plug>(caw:hatpos:toggle)
  vmap <C-_> <Plug>(caw:hatpos:toggle)
'''

# Git 周りをいい感じに
[[plugins]]
repo = 'tpope/vim-fugitive'

